// <auto-generated />
using BookMyStay.ListingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMyStay.ListingAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231118074012_CreateListingTableWithData")]
    partial class CreateListingTableWithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMyStay.ListingAPI.Models.Listing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListingPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListingId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            ListingId = 1,
                            Category = "Small Villa",
                            Description = "Stay away from the city nuisance in midst of green lush. Choose from 5 small vintage houses in middle of the Bawana Jungle, which welcomes you for a cozy stay.",
                            ImageUrl = "https://i.ibb.co/C5x9cS4/pic1.jpg",
                            ListingPrice = 599.99000000000001,
                            Name = "Vintage Houses In Jungle"
                        },
                        new
                        {
                            ListingId = 2,
                            Category = "Small Cabin",
                            Description = "Pick a nice wooden cabin for your next camping on top of the Hidler mountain range. Enough for 4 people's stay with lots of fun time for youe camping without a tent.",
                            ImageUrl = "https://i.ibb.co/0XgMrWj/pic2.jpg",
                            ListingPrice = 499.99000000000001,
                            Name = "Wooden Cabins On Mountain"
                        },
                        new
                        {
                            ListingId = 3,
                            Category = "Large Villa",
                            Description = "Beautiful raw villa houses for a pleasant weekend spend near the Kilana lake, comes with all modern amenities and yet gives a rural feeling on your stay. Ideal for a family of 2-6 people.",
                            ImageUrl = "https://i.ibb.co/9NMM4vz/pic3.jpg",
                            ListingPrice = 1299.99,
                            Name = "Villa Houses On Rent"
                        },
                        new
                        {
                            ListingId = 4,
                            Category = "Large Villa",
                            Description = "Beautiful modern villa houses for a lavish stay during your business trip, comes with all modern amenities and comfort. Very accessible from the Arila and Garmdos airports and Firana city railway stations. Ideal for corporate meetings and small events",
                            ImageUrl = "https://i.ibb.co/cNgwSyw/pic4.jpg",
                            ListingPrice = 1999.99,
                            Name = "Lush Houses For Business People"
                        },
                        new
                        {
                            ListingId = 5,
                            Category = "Large Villa",
                            Description = "Beautiful modern bunglow for throwing lavish parties or arrange team events.Very accessible from the Arila and Garmdos airports and Firana city railway stations. Best choice for large corporate or family events.",
                            ImageUrl = "https://i.ibb.co/JtVSssw/pic5.jpg",
                            ListingPrice = 3499.9899999999998,
                            Name = "Bunglow For Events"
                        },
                        new
                        {
                            ListingId = 6,
                            Category = "Small Villa",
                            Description = "Beautiful modern guest houses with all modern equipments, suitable for both business and pleasure of the guests. Accessible and affordable providing best value for money.",
                            ImageUrl = "https://i.ibb.co/sKv6Sr9/pic6.jpg",
                            ListingPrice = 899.99000000000001,
                            Name = "Corporate Guest Houses"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
