// <auto-generated />
using System;
using BookMyStay.PaymentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMyStay.PaymentAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231230054839_AddPaymentTablesToDB")]
    partial class AddPaymentTablesToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMyStay.PaymentAPI.Models.PaymentItem", b =>
                {
                    b.Property<int>("BookingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingItemId"));

                    b.Property<double>("BookingTotal")
                        .HasColumnType("float");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfferCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingItemId");

                    b.ToTable("PaymentItem");
                });

            modelBuilder.Entity("BookMyStay.PaymentAPI.Models.PaymentItemDetails", b =>
                {
                    b.Property<int>("PaymentItemDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentItemDetailId"));

                    b.Property<double>("BookingPrice")
                        .HasColumnType("float");

                    b.Property<int>("DayOfStay")
                        .HasColumnType("int");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentItemId")
                        .HasColumnType("int");

                    b.HasKey("PaymentItemDetailId");

                    b.HasIndex("PaymentItemId");

                    b.ToTable("PaymentItemDetails");
                });

            modelBuilder.Entity("BookMyStay.PaymentAPI.Models.PaymentItemDetails", b =>
                {
                    b.HasOne("BookMyStay.PaymentAPI.Models.PaymentItem", "PaymentItem")
                        .WithMany("PaymentItemDetails")
                        .HasForeignKey("PaymentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentItem");
                });

            modelBuilder.Entity("BookMyStay.PaymentAPI.Models.PaymentItem", b =>
                {
                    b.Navigation("PaymentItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
